"
" ~/.vim/vimrc
"

set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on

set background=dark

set viminfo+=n~/.vim/viminfo
set hidden
set undofile
set undodir=~/.vim/undo/
set clipboard=unnamedplus

set number
set relativenumber
set cursorline
set cursorcolumn

highlight CursorLine   ctermbg=Black                cterm=NONE
highlight CursorColumn ctermbg=Black                cterm=NONE
highlight Comment                                   cterm=italic
highlight TabLineFill  ctermbg=Green ctermfg=Black
highlight TabLine      ctermbg=Black ctermfg=Green
highlight TabLineSel   ctermbg=Black ctermfg=Red
highlight StatusLine   ctermbg=Red   ctermfg=Black
highlight StatusLineNC ctermbg=Red   ctermfg=Black
highlight VertSplit    ctermbg=Red   ctermfg=Black
highlight LineNr       ctermbg=NONE  ctermfg=Red    cterm=NONE
highlight CursorLineNr ctermbg=NONE  ctermfg=Red    cterm=italic

set showcmd
set showmode
set noshowmatch

set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set scrolloff=5
set nowrap
set incsearch
set ignorecase
set smartcase
set wildmenu
set lazyredraw
set listchars=tab:>-,trail:·,nbsp:_

"///////////
"/ PLUGINS /////////////////////////////////////////////////////////////////////
"///////////

call plug#begin()
Plug 'amadeus/vim-convert-color-to'
Plug 'ap/vim-css-color'
Plug 'dylanaraps/fff.vim'
Plug 'glts/vim-magnum'
Plug 'glts/vim-radical'
Plug 'junegunn/vim-easy-align'
Plug 'mattn/calendar-vim'
Plug 'psliwka/vim-smoothie'
Plug 'sersorrel/vim-lilypond'
Plug 'sheerun/vim-polyglot'
Plug 'svermeulen/vim-subversive'
Plug 'svermeulen/vim-yoink'
Plug 'tommcdo/vim-exchange'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tridactyl/vim-tridactyl'
Plug 'vimwiki/vimwiki'
Plug 'wellle/targets.vim'
call plug#end()

"/////////////
"/ FUNCTIONS ///////////////////////////////////////////////////////////////////
"/////////////

function! COptions()
    setlocal commentstring=//\ %s
    if filereadable(expand("./build.sh"))
        setlocal makeprg=./buildh.sh\ %
    elseif filereadable(expand("~/prog/c/build.sh"))
        setlocal makeprg=~/prog/c/build.sh\ %
    endif
endfunction

"///////////////////
"/ CUSTOM MAPPINGS /////////////////////////////////////////////////////////////
"///////////////////

let mapleader = " "

nnoremap j gj
nnoremap k gk

" Toggle show whitespace
noremap <F3> :set list!<CR>
"Remove all trailing whitespace
nnoremap <F4> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" Disable/enable automatic comments
nnoremap <Leader>c :set formatoptions-=cro<CR>
nnoremap <Leader>C :set formatoptions+=cro<CR>


"////////////////////
"/ PLUG-IN MAPPINGS ////////////////////////////////////////////////////////////
"////////////////////

" EASY-ALIGN
nmap gq <Plug>(EasyAlign)
xmap gq <Plug>(EasyAlign)

" SUBVERSIVE
" Normal:
nmap s           <Plug>(SubversiveSubstitute)
nmap ss          <Plug>(SubversiveSubstituteLine)
nmap S           <Plug>(SubversiveSubstituteToEndOfLine)
nmap <Leader>s   <Plug>(SubversiveSubvertRange)
nmap <Leader>ss  <Plug>(SubversiveSubvertWordRange)
nmap <Leader>cs  <Plug>(SubversiveSubstituteRangeConfirm)
nmap <Leader>css <Plug>(SubversiveSubstituteWordRangeConfirm)
" Visual:
xmap <Leader>s  <Plug>(SubversiveSubvertRange)
xmap s          <Plug>(SubversiveSubstitute)
xmap p          <Plug>(SubversiveSubstitute)
xmap P          <Plug>(SubversiveSubstitute)
xmap <Leader>cs <Plug>(SubversiveSubstituteRangeConfirm)

" YOINK
nmap <C-n> <Plug>(YoinkPostPasteSwapBack)
nmap <C-p> <Plug>(YoinkPostPasteSwapForward)
nmap p     <Plug>(YoinkPaste_p)
nmap P     <Plug>(YoinkPaste_P)
nmap gp    <Plug>(YoinkPaste_gp)
nmap gP    <Plug>(YoinkPaste_gP)


" MAGNUM
" gA  - Shows the four representations of the number under the cursor (or selected in Visual mode).
" crd - Convert to decimal
" crx - Convert to hex
" cro - Convert to octal
" crb - Convert to binary

" EXCHANGE
" Normal:
" cx + motion - Exchange
" cxx         - Exchange line
" Visual:
" X           - Exchange selection

" COMMENTARY
" Normal:
" gcc - Comment out a line
" Visual:
" gc  - Comment out a selection


"///////////
"/ OPTIONS /////////////////////////////////////////////////////////////////////
"///////////

" VIMWIKI
" Use .md files for vimwiki
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
" Disable parenhesis highlighting
let g:loaded_matchparen=1

" EASY-ALIGN
" Also align comments
let g:easy_align_ignore_unmatched = 0

"////////////
"/ AUTOCMDS ////////////////////////////////////////////////////////////////////
"////////////

command! Diary VimwikiDiaryIndex
augroup vimwikigroup
    autocmd!
    " Automatically update links on read diary
    autocmd BufRead,BufNewFile diary.wiki VimwikiDiaryGenerateLinks
augroup end

" PHP File Types (WordPress, use tabs)
autocmd FileType php set noexpandtab

autocmd Filetype c call COptions()
